### ISSUE TITLE
TypeError: the promise constructor cannot be invoked directly

### ISSUE THREAD

**Issue by mcraz** [poppinss/indicative#174]
I get this error when I validate. No matter what data is passed. I get the same exact error.

Code
```
return validateAll({}, {'something': 'required'}).catch(errors => {
    console.log(errors);
})
```

Output
```
TypeError: the promise constructor cannot be invoked directly

    See http://goo.gl/MqrFmX

    at check (/Users/a/b/c/node_modules/bluebird/js/release/promise.js:62:15)
    at PLazy.Promise (/Users/a/b/c/node_modules/bluebird/js/release/promise.js:72:9)
    at PLazy (/Users/a/b/c/node_modules/p-lazy/index.js:5:3)
    at Object.ValidationEngine.runValidationOnField (/Users/a/b/c/node_modules/indicative/src/Validator/engine.js:57:10)
    at _.map (/Users/a/b/c/node_modules/indicative/src/Validator/engine.js:36:29)
    at arrayMap (/Users/a/b/c/node_modules/lodash/lodash.js:660:23)
    at Function.map (/Users/a/b/c/node_modules/lodash/lodash.js:9571:14)
    at Object.ValidationEngine.validateField (/Users/a/b/c/node_modules/indicative/src/Validator/engine.js:35:28)
    at _.map (/Users/a/b/c/node_modules/indicative/src/Validator/index.js:38:29)
    at /Users/a/b/c/node_modules/lodash/lodash.js:3554:27
    at /Users/a/b/c/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/Users/a/b/c/node_modules/lodash/lodash.js:3001:24)
    at /Users/a/b/c/node_modules/lodash/lodash.js:4913:18
    at baseMap (/Users/a/b/c/node_modules/lodash/lodash.js:3553:7)
    at Function.map (/Users/a/b/c/node_modules/lodash/lodash.js:9571:14)
    at _mapValidations (/Users/a/b/c/node_modules/indicative/src/Validator/ind
```

**Comment by mcraz** [comment]
Nevermind. I was overriding the global Promise object with bluebird. Removing that solves it.
