### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by tomerb15** [poppinss/indicative#33]
Hey,

The following code:

```
var paramsObj = {
        phone: "111111111111"
        appid: 0
        timestamp: "1447146467120"
        text: "some text"
    };

    //Validate the parameters
    var rules = {
        phone: 'required|regex:^[0-9]*$',
        appid:'integer',
        timestamp:'required',
        text:'requires|string'
    };


    Indicative.validate(rules,paramsObj)
        .then(function(success){
            console.log(success);
        }).catch(function(err){
            console.log(err);
        }).done();
```

is throwing the following exception when the validation is passed:

```
Unhandled rejection TypeError: Cannot read property 'call' of undefined
    at /Users/tomerb15/WebstormProjects/chatDel/node_modules/indicative/lib/validator.js:70:40
    at tryCatcher (/Users/tomerb15/WebstormProjects/chatDel/node_modules/indicative/node_modules/bluebird/js/main/util.js:26:23)
    at ReductionPromiseArray.module.exports.ReductionPromiseArray._promiseFulfilled (/Users/tomerb15/WebstormProjects/chatDel/node_modules/indicative/node_modules/bluebird/js/main/reduce.js:109:18)
    at ReductionPromiseArray.init (/Users/tomerb15/WebstormProjects/chatDel/node_modules/indicative/node_modules/bluebird/js/main/promise_array.js:92:18)
    at ReductionPromiseArray.init (/Users/tomerb15/WebstormProjects/chatDel/node_modules/indicative/node_modules/bluebird/js/main/reduce.js:42:10)
    at Async._drainQueue (/Users/tomerb15/WebstormProjects/chatDel/node_modules/indicative/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/tomerb15/WebstormProjects/chatDel/node_modules/indicative/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.__dirname.drainQueues [as _onImmediate] (/Users/tomerb15/WebstormProjects/chatDel/node_modules/indicative/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Which is originated from validator.js:70:40:

```
return self.validations[rule].call(self, data, field, message, args)["catch"](function(message) {
```

**Comment by thetutlage** [comment]
There is a typo `text:'requires|string'` has to be `text:'required|string'`

**Comment by tomerb15** [comment]
great catch, thanks!
