### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by nivv** [poppinss/indicative#39]
My package.json

```
{
  "name": "adonis-app",
  "version": "1.0.0",
  "description": "Folder structure for adonis application",
  "main": "server.js",
  "scripts": {
    "start": "node --harmony_proxies server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "adonis-ace": "^1.0.3",
    "adonis-commands": "^1.0.4",
    "adonis-config-provider": "^1.0.3",
    "adonis-fold": "^1.0.6",
    "adonis-framework": "^1.1.2",
    "adonis-lucid": "^1.0.3",
    "adonis-validation-provider": "^1.0.1",
    "formidable": "^1.0.17",
    "ouch": "^0.2.0-beta",
    "raw-body": "^2.1.2"
  },
  "autoload": {
    "App": "./app"
  },
  "devDependencies": {
    "sqlite3": "^3.1.0"
  }
}
```

Output when I run `npm install`

```
> indicative@1.3.1 postinstall /Users/u1/dev/heroku-node/node_modules/indicative
> coffee -c .

/Users/u1/dev/heroku-node/node_modules/indicative/lib/extendedRules.coffee:83:10: error: "offset = 0" cannot be assigned
        [offset = 0,key = 'days'] = args.toString().split ","
         ^^^^^^^^^^
479 verbose stack Error: indicative@1.3.1 postinstall: `coffee -c .`
479 verbose stack Exit status 1
479 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
479 verbose stack     at emitTwo (events.js:87:13)
479 verbose stack     at EventEmitter.emit (events.js:172:7)
479 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
479 verbose stack     at emitTwo (events.js:87:13)
479 verbose stack     at ChildProcess.emit (events.js:172:7)
479 verbose stack     at maybeClose (internal/child_process.js:818:16)
479 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
480 verbose pkgid indicative@1.3.1
481 verbose cwd /Users/albin/dev/heroku-node
482 error Darwin 15.0.0
483 error argv "/usr/local/Cellar/node/0.12.4/bin/node" "/usr/local/bin/npm" "install"
484 error node v5.0.0
485 error npm  v3.3.6
486 error code ELIFECYCLE
487 error indicative@1.3.1 postinstall: `coffee -c .`
487 error Exit status 1
488 error Failed at the indicative@1.3.1 postinstall script 'coffee -c .'.
488 error This is most likely a problem with the indicative package,
488 error not with npm itself.
488 error Tell the author that this fails on your system:
488 error     coffee -c .
488 error You can get their info via:
488 error     npm owner ls indicative
488 error There is likely additional logging output above.
489 verbose exit [ 1, true ]
```

My node version: `node -v v5.0.0`
My npm version: `npm -v 3.3.6`

**Comment by thetutlage** [comment]
Which operating system are u on ?

**Comment by nivv** [comment]
@thetutlage Tested on Ubuntu 14.04 and OSX El capitan

**Comment by thetutlage** [comment]
Weird, will you try to install `adonis-validation-provider` separately by saying 

```
npm install --save adonis-validation-provider
```

**Comment by FabienMotte** [comment]
Same error here (OSX El Capitan), even when installed separetely
Node version : `v5.1.1`
NPM version : `v3.3.12`

**Comment by thetutlage** [comment]
Fixed, now `adonis-validation-provider` uses latest version of `indicative`
