### ISSUE TITLE
Calling `normalizeEmail()` without a second argument yields "TypeError: Cannot read property 'forEach' of undefined"

### ISSUE THREAD

**Issue by nicklaw5** [poppinss/indicative#67]
I'm using the Adonis Framework, but this is an issue related to Indicative.

As provided in Adonis' [sanitizor example](http://adonisjs.com/docs/3.0/validator#sanitizor), calling this:

``` js
const sanitizedEmail = Validator.sanitizor.normalizeEmail('bar.sneaky+foo@googlemail.com')
```

Generates this error stack:

``` txt
TypeError: Cannot read property 'forEach' of undefined
    at Object.SanitizationFilters.normalizeEmail (/home/nick/Code/workremotely.online-adonis/node_modules/indicative/src/Sanitization/filters.js:112:7)
    at UsersController.store (/home/nick/Code/workremotely.online-adonis/app/Http/Controllers/Api/UsersController.js:22:38)
    at next (native)
    at /home/nick/Code/workremotely.online-adonis/node_modules/adonis-framework/src/Middleware/index.js:207:20
    at next (native)
    at onFulfilled (/home/nick/Code/workremotely.online-adonis/node_modules/co/index.js:65:19)
    at /home/nick/Code/workremotely.online-adonis/node_modules/co/index.js:54:5
    at co (/home/nick/Code/workremotely.online-adonis/node_modules/co/index.js:50:10)
    at toPromise (/home/nick/Code/workremotely.online-adonis/node_modules/co/index.js:118:63)
    at next (/home/nick/Code/workremotely.online-adonis/node_modules/co/index.js:99:29)
    at onFulfilled (/home/nick/Code/workremotely.online-adonis/node_modules/co/index.js:69:7)
    at /home/nick/Code/workremotely.online-adonis/node_modules/co/index.js:54:5
    at co (/home/nick/Code/workremotely.online-adonis/node_modules/co/index.js:50:10)
    at Server._executeChain (/home/nick/Code/workremotely.online-adonis/node_modules/adonis-framework/src/Server/index.js:176:12)
    at Server._callRouteAction (/home/nick/Code/workremotely.online-adonis/node_modules/adonis-framework/src/Server/index.js:75:17)
    at finalHandler (/home/nick/Code/workremotely.online-adonis/node_modules/adonis-framework/src/Server/index.js:246:18)
```

**Comment by thetutlage** [comment]
Done in related PR
