### ISSUE TITLE
Unhandled rejection Error

### ISSUE THREAD

**Issue by gRoberts84** [poppinss/indicative#7]
Hey there,

Trying to use Indicative and Mongoose to validate and insert some data into MongoDB but keep on being hit with an `unhandled rejection error` exception.

```
var user = new model.User(req.body);
    user.validate(req.body).then(function(x) {

        user.save(function(err) {
            if (err) {
                res.send(new restify.errors.BadRequestError());
            } else {
                res.send({
                    userId: user._id
                })
            }
        });

    }).catch(function(err) {
        res.send(new restify.errors.BadRequestError());
        return next();
    }).done();
```

It seems as soon as I call user.save, it throws:

```
Unhandled rejection Error: [object Object],[object Object],[object Object]
    at Object.ensureErrorObject (/home/ubuntu/workspace/node_modules/indicative/node_modules/bluebird/js/main/util.js:232:20)
    at Promise._rejectCallback (/home/ubuntu/workspace/node_modules/indicative/node_modules/bluebird/js/main/promise.js:416:22)
    at /home/ubuntu/workspace/node_modules/indicative/node_modules/bluebird/js/main/promise.js:433:17
    at /home/ubuntu/workspace/node_modules/indicative/lib/validator.js:114:20
    at /home/ubuntu/workspace/node_modules/indicative/node_modules/async/lib/async.js:304:13
    at done (/home/ubuntu/workspace/node_modules/indicative/node_modules/async/lib/async.js:132:19)
    at /home/ubuntu/workspace/node_modules/indicative/node_modules/async/lib/async.js:32:16
    at /home/ubuntu/workspace/node_modules/indicative/node_modules/async/lib/async.js:301:17
    at /home/ubuntu/workspace/node_modules/indicative/lib/validator.js:107:18
    at tryCatcher (/home/ubuntu/workspace/node_modules/indicative/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/node_modules/indicative/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/home/ubuntu/workspace/node_modules/indicative/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/home/ubuntu/workspace/node_modules/indicative/node_modules/bluebird/js/main/promise.js:646:14)
    at Promise.b (domain.js:183:18)
    at Async._drainQueue (/home/ubuntu/workspace/node_modules/indicative/node_modules/bluebird/js/main/async.js:187:12)
    at Async._drainQueues (/home/ubuntu/workspace/node_modules/indicative/node_modules/bluebird/js/main/async.js:192:10)
    at Async.drainQueues (/home/ubuntu/workspace/node_modules/indicative/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickDomainCallback (node.js:486:13)
```

FYI, user.validate is simply a prototype method of my mongoose model:

```
var mongoose = require('mongoose'),
    Indicative = require('indicative'),
    indicative = new Indicative();

var userSchema = new mongoose.Schema({
    email: String,
    forename: String,
    surname: String,
    username: String,
    password: String,
    source: String,
    profileImage: String,
    packageId: Number,
    oAuth: {
        userId: Number,
        token: String
    }
});

var User = mongoose.model('User', userSchema);

User.prototype.validate = function(data) {

    var rules = {
        email     :  'required|email',
        password  :  'required',
        packageId :  'required|number'
    }

    return indicative.validateAll(rules, data);

}

module.exports = {
  User: User
}
```

Am I completely missing something here?

Thanks

Gavin

**Comment by thetutlage** [comment]
What happens when you don't call the save method and console `x`

**Comment by gRoberts84** [comment]
Hey, 

It spits out the data passed to validateAll. 

The weird thing is that in the stack trace it refers to line 114 of validate.js. If I pass valid data the issue happens, if I pass invalid data it calls the catch callback. 

I'm mobile at the moment but I'll try running save without including indicative and see how it goes. 

Thanks

Gav

**Comment by thetutlage** [comment]
Make sense, i am not a Mongo guy , but will install it on a Vagrant machine to test the issue

**Comment by gRoberts84** [comment]
Hey there,

Well, after removing the require and instantiation of Indicative, it works (without):

```
var user = new model.User(req.body);
    user.save(function(err) {
        if (err) res.send(err, 500);
        res.send('success');
    });
```

The above works nicely, and in my mongoose model, commenting out the Indicative require and instantiation fixed it.

```
var mongoose = require('mongoose')/*,
    Indicative = require('indicative'),
    indicative = new Indicative()*/;
```

It looks like Bluebird is conflicting however I have read that by Promisifying Mongoose, it should work.

Watch this space :)

**Comment by gRoberts84** [comment]
So.. It looks like it was my own fault... What a pleb.

Mongoose has it's own validation built in and when I was calling validate on the mongoose model object it somehow was calling it on both my prototype and the internal validation.

As soon as I changed the prototype function name and called that instead, everything worked rosey!

```
server.post('/api/user', function(req, res, next) {
    var user = new model.User(req.body);
    user.xValidate(req.body).then(function(x) {
        user.saveAsync().then(function(x) {
            console.log([x, 'SUCCESS']);
        }).catch(function(x) {
            console.log([x, 'ERROR']);
        });
    }).catch(function(x) {
        console.log([x, 'ERROR']);
    });
});
```

Thank you for your help :)
